name: unicode_emojis
description: Unicode 15.0 emojis with metadata, search and skin tone support.
version: 0.2.0
repository: https://github.com/merrit/unicode_emojis
funding:
  - https://merritt.codes/support/
  - https://github.com/sponsors/Merrit?o=esb

environment:
  sdk: ^3.0.2

dependencies:
  collection: ^1.17.1

dev_dependencies:
  http: ^1.0.0
  lints: ^2.0.0
  test: ^1.21.0
